apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: webapp
    patch: |
      - op: add
        path: /metadata/annotations/moda.github.net~1domain-name
        value: 'docs-staging-saturn226.service.%region%.github.net'
