apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: webapp
    patch: |
      - op: add
        path: /metadata/annotations/moda.github.net~1domain-name
        value: 'docs.internal.github.com'
      - op: add
        path: /metadata/annotations/moda.github.net~1dns-registration-enabled
        value: 'false'
      - op: add
        path: /metadata/annotations/moda.github.net~1load-balancer-type
        value: 'public-external-http'
